INSERT INTO "FUNCTIONINFO" VALUES ('141', '视频监控', NULL, '14', NULL, NULL, '1', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('521', '远程控制', NULL, '52', NULL, NULL, '5', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('6', '展示', NULL, NULL, NULL, NULL, '6', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('11', '岸基在线监测站', NULL, '#', '#', NULL, '1', 'glyphicon glyphicon-home');
INSERT INTO "FUNCTIONINFO" VALUES ('12', '浮标在线监控站', NULL, '#', '#', NULL, '1', 'glyphicon glyphicon-map-marker');
INSERT INTO "FUNCTIONINFO" VALUES ('13', '遥感监测', NULL, '#', '#', NULL, '1', 'glyphicon glyphicon-globe');
INSERT INTO "FUNCTIONINFO" VALUES ('14', '视频监控', NULL, '#', '#', NULL, '1', 'glyphicon glyphicon-film');
INSERT INTO "FUNCTIONINFO" VALUES ('21', '入海污染源', NULL, '#', '#', NULL, '2', 'glyphicon glyphicon-asterisk');
INSERT INTO "FUNCTIONINFO" VALUES ('22', '海洋环境', NULL, '#', '#', NULL, '2', 'glyphicon glyphicon-tree-deciduous');
INSERT INTO "FUNCTIONINFO" VALUES ('23', '海洋生态红线管理', NULL, '#', '#', NULL, '2', 'glyphicon glyphicon-th-large');
INSERT INTO "FUNCTIONINFO" VALUES ('31', '局属设施', NULL, '#', '#', NULL, '3', 'glyphicon glyphicon-star');
INSERT INTO "FUNCTIONINFO" VALUES ('32', '地方设施', NULL, '#', '#', NULL, '3', 'glyphicon glyphicon-star-empty');
INSERT INTO "FUNCTIONINFO" VALUES ('41', '海区', NULL, '#', '#', NULL, '4', 'glyphicon glyphicon-saved');
INSERT INTO "FUNCTIONINFO" VALUES ('42', '省份', NULL, '#', '#', NULL, '4', 'glyphicon glyphicon-record');
INSERT INTO "FUNCTIONINFO" VALUES ('43', '海湾', NULL, '#', '#', NULL, '4', 'glyphicon glyphicon-refresh');
INSERT INTO "FUNCTIONINFO" VALUES ('51', '监测手段', NULL, '#', '#', '1', '5', 'glyphicon glyphicon-random');
INSERT INTO "FUNCTIONINFO" VALUES ('52', '远程控制', NULL, '#', '#', NULL, '5', 'glyphicon glyphicon-wrench');
INSERT INTO "FUNCTIONINFO" VALUES ('53', '报告管理', NULL, '#', '#', NULL, '5', 'glyphicon glyphicon-calendar');
INSERT INTO "FUNCTIONINFO" VALUES ('54', '数据审核', NULL, '#', '#', NULL, '5', 'glyphicon glyphicon-list-alt');
INSERT INTO "FUNCTIONINFO" VALUES ('55', '操作日志', NULL, '#', '#', NULL, '5', 'glyphicon glyphicon-pencil');
INSERT INTO "FUNCTIONINFO" VALUES ('56', '系统管理', NULL, '#', '#', NULL, '5', 'glyphicon glyphicon-cog');
INSERT INTO "FUNCTIONINFO" VALUES ('111', '统计分析', NULL, '11', 'DeviceInfoList?type=1&class=2', NULL, '1', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('112', '三维展示', NULL, '11', 'DeviceInfoList?type=1&class=4', NULL, '1', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('113', '数据监控', NULL, '11', 'DeviceInfoList?type=1&class=1', NULL, '1', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('114', '岸房视频监控', NULL, '11', 'DeviceInfoList?type=1&class=3', NULL, '1', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('115', '作业流程监控', NULL, '11', 'DeviceInfoList?type=1&class=5', NULL, '1', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('121', '统计分析', NULL, '12', 'DeviceInfoList?type=2&class=2', NULL, '1', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('122', '数据监控', NULL, '12', 'DeviceInfoList?type=2&class=1', NULL, '1', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('123', '浮标视频监控', NULL, '12', 'DeviceInfoList?type=2&class=3', NULL, '1', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('131', '无人机', NULL, '13', NULL, NULL, '1', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('132', '遥感影像', NULL, '13', NULL, NULL, '1', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('211', '入海排污口', NULL, '21', '#', '1', '2', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('212', '入海江河', NULL, '21', '#', '1', '2', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('213', '海洋工程', NULL, '21', '#', '1', '2', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('221', '环境风险', NULL, '22', '#', '1', '2', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('222', '重点海湾', NULL, '22', '#', '1', '2', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('223', '海洋保护区', NULL, '22', '#', '1', '2', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('311', '北海监测中心', NULL, '31', '#', '1', '3', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('312', '大连中心站', NULL, '31', '#', '1', '3', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('313', '秦皇岛中心站', NULL, '31', '#', '1', '3', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('314', '天津中心站', NULL, '31', '#', '1', '3', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('315', '烟台中心站', NULL, '31', '#', '1', '3', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('316', '青岛中心站', NULL, '31', '#', '1', '3', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('321', '辽宁省海洋与渔业厅', NULL, '32', '#', '1', '3', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('322', '河北省海洋局', NULL, '32', '#', '1', '3', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('323', '天津市海洋局', NULL, '32', '#', '1', '3', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('324', '山东省海洋与渔业厅', NULL, '32', '#', '1', '3', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('325', '大连市海洋与渔业局', NULL, '32', '#', '1', '3', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('326', '青岛市海洋与渔业局', NULL, '32', '#', '1', '3', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('411', '渤海', NULL, '41', '#', '1', '4', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('412', '黄海', NULL, '41', '#', '1', '4', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('421', '河北省', NULL, '42', '#', '1', '4', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('422', '天津市', NULL, '42', '#', '1', '4', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('423', '山东省', NULL, '42', '#', '1', '4', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('424', '大连市', NULL, '42', '#', '1', '4', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('425', '青岛市', NULL, '42', '#', '1', '4', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('431', '辽东湾', NULL, '43', '#', '1', '4', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('432', '渤海湾', NULL, '43', '#', '1', '4', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('433', '莱州湾', NULL, '43', '#', '1', '4', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('434', '大连湾', NULL, '43', '#', '1', '4', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('435', '胶州湾', NULL, '43', '#', '1', '4', 'glyphicon glyphicon-tag');
INSERT INTO "FUNCTIONINFO" VALUES ('231', '监测手段', NULL, '23', '#', '1', '2', 'glyphicon glyphicon-random');
INSERT INTO "FUNCTIONINFO" VALUES ('531', '岸基站监测报告', NULL, '53', NULL, NULL, '5', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('532', '浮标监测报告', NULL, '53', NULL, NULL, '5', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('533', '遥感监测报告', NULL, '53', NULL, NULL, '5', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('541', '市级审核', NULL, '54', NULL, NULL, '5', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('542', '省级审核', NULL, '54', NULL, NULL, '5', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('543', '北海分局审核', NULL, '54', NULL, NULL, '5', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('551', '数据审核日志', NULL, '55', NULL, NULL, '5', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('552', '系统操作日志', NULL, '55', NULL, NULL, '5', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('561', '机构管理', NULL, '56', NULL, NULL, '5', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('562', '角色管理', NULL, '56', NULL, NULL, '5', NULL);
INSERT INTO "FUNCTIONINFO" VALUES ('563', '用户管理', NULL, '56', NULL, NULL, '5', NULL);
